# Generated by Django 3.2.14 on 2022-08-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('barcode_file', models.CharField(choices=[('barcode_set1.csv', 'barcode_set1.csv')], max_length=200)),
                ('adapter_file', models.CharField(max_length=200)),
                ('chrom_sizes', models.CharField(max_length=200)),
                ('star_index', models.CharField(max_length=200)),
                ('umi_pattern', models.CharField(max_length=200)),
                ('fastqs', models.CharField(max_length=200)),
            ],
        ),
    ]
