# Generated by Django 3.2.14 on 2022-09-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fast',
            new_name='Fastq',
        ),
    ]
