# Generated by Django 3.2.14 on 2022-08-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CLIP',
        ),
    ]
