# Generated by Django 4.1 on 2022-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clip_fastq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='adapter_file',
        ),
        migrations.AddField(
            model_name='fastq',
            name='adapter_path',
            field=models.CharField(blank=True, choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta')], max_length=50),
        ),
        migrations.AddField(
            model_name='fastq',
            name='path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clip',
            name='barcode_file',
            field=models.CharField(blank=True, choices=[('barcode_set1.csv', 'barcode_set1.csv')], max_length=25),
        ),
        migrations.AlterField(
            model_name='clip',
            name='chrom_sizes',
            field=models.CharField(blank=True, choices=[('hg38.chrom.sizes', 'hg38.chrom.sizes'), ('hg19.chrom.sizes', 'hg19.chrom.sizes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clip',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clip',
            name='fastqs',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clip',
            name='star_index',
            field=models.CharField(blank=True, choices=[('star_2_7_gencode29_sjdb', 'star_2_7_gencode29_sjdb'), ('star_2_7_6a_release6_sjdb', 'star_2_7_6a_release6_sjdb')], max_length=50),
        ),
    ]
