# Generated by Django 3.2.15 on 2022-09-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220921_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIPManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('species', models.CharField(blank=True, choices=[('hg19', 'hg19'), ('GRCh38_v40', 'GRCh38_v40')], max_length=20)),
                ('barcode_file', models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta')], max_length=90)),
                ('chrom_sizes', models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', 'star_2_7_gencode40_sjdb/ (GRCh38) (must match genome)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/chrNameLength.txt', 'star_2_7_6a_gencode19_sjdb/ (hg19) (must match genome)')], max_length=120)),
                ('star_index', models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/', 'star_2_7_6a_gencode19_sjdb/ (hg19)')], max_length=90)),
                ('umi_pattern', models.CharField(default='NNNNNNNNNN', max_length=10)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CLIP',
        ),
    ]
