# Generated by Django 3.2.14 on 2022-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_clip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('barcode_file', models.CharField(choices=[('barcode_set1.csv', 'barcode_set1.csv')], max_length=25)),
                ('adapter_file', models.CharField(choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta')], max_length=50)),
                ('chrom_sizes', models.CharField(choices=[('hg38.chrom.sizes', 'hg38.chrom.sizes'), ('hg19.chrom.sizes', 'hg19.chrom.sizes')], max_length=50)),
                ('star_index', models.CharField(choices=[('star_2_7_gencode29_sjdb', 'star_2_7_gencode29_sjdb'), ('star_2_7_6a_release6_sjdb', 'star_2_7_6a_release6_sjdb')], max_length=50)),
                ('umi_pattern', models.CharField(max_length=10)),
                ('fastqs', models.CharField(max_length=200)),
            ],
        ),
    ]
