# Generated by Django 3.2.14 on 2022-08-25 23:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='star_index',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('star_2_7_gencode29_sjdb', 'star_2_7_gencode29_sjdb'), ('star_2_7_6a_release6_sjdb', 'star_2_7_6a_release6_sjdb')], max_length=49),
        ),
    ]
