# Generated by Django 3.2.15 on 2022-09-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220921_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastq',
            old_name='adapter_path',
            new_name='ip_adapter_path',
        ),
        migrations.RenameField(
            model_name='fastq',
            old_name='complete',
            new_name='ip_complete',
        ),
        migrations.RenameField(
            model_name='fastq',
            old_name='path',
            new_name='ip_path',
        ),
        migrations.RenameField(
            model_name='fastq',
            old_name='title',
            new_name='ip_title',
        ),
        migrations.AddField(
            model_name='clipmanifest',
            name='repeat_index',
            field=models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2', 'star_2_7_homo_sapiens_repbase_fixed_v2'), ('/projects/ps-yeolab3/bay001/annotations/RepBase18.05/star_2_7_mus_musculus_repbase_fixed_v2', 'star_2_7_mus_musculus_repbase_fixed_v2')], max_length=120),
        ),
        migrations.AddField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(default='', max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastq',
            name='sminput_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastq',
            name='sminput_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fastq',
            name='sminput_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clipmanifest',
            name='barcode_file',
            field=models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta')], max_length=120),
        ),
        migrations.AlterField(
            model_name='clipmanifest',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clipmanifest',
            name='umi_pattern',
            field=models.CharField(default='NNNNNNNNNN', max_length=20),
        ),
    ]
