# Generated by Django 4.1.1 on 2022-09-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_dataset_clipmanifest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastq',
            name='ip_adapter_path',
            field=models.CharField(default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=90),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=90),
        ),
    ]
