# Generated by Django 4.1.1 on 2022-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_fastq_ip_adapter_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipmanifest',
            name='exclusion_file',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', '/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed')], default='/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', max_length=120),
        ),
    ]
