# Generated by Django 4.1.1 on 2022-09-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_clipmanifest_exclusion_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipmanifest',
            old_name='repeat_index',
            new_name='repeatElementGenomeDir',
        ),
        migrations.RenameField(
            model_name='clipmanifest',
            old_name='star_index',
            new_name='speciesGenomeDir',
        ),
        migrations.RemoveField(
            model_name='clipmanifest',
            name='exclusion_file',
        ),
        migrations.AddField(
            model_name='clipmanifest',
            name='blacklist_file',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', 'eCLIP_blacklistregions.hg38liftover.bed.fixed.bed')], default='/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', max_length=120),
        ),
    ]
