# Generated by Django 4.1.1 on 2022-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_name_clipmanifest_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipperConfigManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/', max_length=200)),
                ('manifest', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/examples/rbfox2_cardiomyocytes.csv', max_length=200)),
                ('gff', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', max_length=200)),
                ('partition', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz', max_length=200)),
                ('feature_annotations', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', max_length=200)),
                ('accession_rankings', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/accession_type_ranking.txt', max_length=200)),
                ('umi_size', models.IntegerField(default=10)),
                ('informative_read', models.IntegerField(default=1)),
                ('overdispersion_mode', models.CharField(default='input', max_length=200)),
                ('conda_dir', models.CharField(default='', max_length=200)),
                ('tool_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/tools', max_length=200)),
                ('exe_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper', max_length=200)),
                ('star_dir', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/', 'star_2_7_6a_gencode19_sjdb/ (hg19)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', max_length=90)),
                ('r_exe', models.CharField(default='/projects/ps-yeolab4/software/yeolabconda3/envs/skipper-8674296/bin/Rscript', max_length=200)),
                ('umicollapse_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/UMICollapse', max_length=200)),
                ('java_exe', models.CharField(default='/projects/ps-yeolab4/software/yeolabconda3/envs/skipper-8674296/bin/java', max_length=200)),
                ('genome', models.CharField(default='/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', max_length=200)),
                ('chrom_sizes', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', 'star_2_7_gencode40_sjdb/ (GRCh38) (must match genome)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/chrNameLength.txt', 'star_2_7_6a_gencode19_sjdb/ (hg19) (must match genome)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', max_length=200)),
                ('repeat_table', models.CharField(default='/projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.tsv.gz', max_length=200)),
                ('blacklist', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_eclip_blacklist.bed', max_length=200)),
                ('gene_sets', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt', max_length=200)),
                ('gene_set_reference', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz', max_length=200)),
                ('gene_set_distance', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds', max_length=200)),
                ('uninformative_read', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SkipperManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fastq',
            name='cells',
            field=models.CharField(default='', max_length=200),
        ),
    ]
