# Generated by Django 4.1.1 on 2022-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_skipperconfigmanifest_skippermanifest_fastq_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='overdispersion_mode',
            field=models.CharField(choices=[('input', 'input'), ('clip', 'clip')], default='input', max_length=200),
        ),
    ]
