# Generated by Django 4.1.1 on 2022-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_skipperconfigmanifest_accession_rankings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipperconfigmanifest',
            name='barcode_file',
            field=models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta')], max_length=120),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='accession_rankings',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='blacklist',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_eclip_blacklist.bed', 'encode3_eclip_blacklist.bed')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_eclip_blacklist.bed', 'encode3_eclip_blacklist.bed'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='feature_annotations',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='gene_set_distance',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds', 'encode3_go_terms.jaccard_index.rds')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds', 'encode3_go_terms.jaccard_index.rds'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='gene_set_reference',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz', 'encode3_go_terms.reference.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz', 'encode3_go_terms.reference.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='gene_sets',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt', 'c5.go.v7.5.1.symbols.gmt')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt', 'c5.go.v7.5.1.symbols.gmt'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='genome',
            field=models.CharField(choices=[('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta')], default=('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='gff',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='overdispersion_mode',
            field=models.CharField(choices=[('input', 'input'), ('clip', 'clip')], default=('input', 'input'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='partition',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='repeat_table',
            field=models.CharField(choices=[('/projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz')], default=('/projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='star_dir',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/', 'star_2_7_6a_gencode19_sjdb/ (hg19)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), max_length=90),
        ),
    ]
