# Generated by Django 4.1.1 on 2022-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_skipperconfigmanifest_barcode_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipperconfigmanifest',
            name='fastqs',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
