# Generated by Django 4.1.1 on 2022-09-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_fastq_experiment_alter_fastq_ip_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastq',
            name='ip_rep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fastq',
            name='sminput_rep',
            field=models.IntegerField(default=1),
        ),
    ]
