# Generated by Django 4.1.1 on 2022-09-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_fastq_ip_rep_fastq_sminput_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='accession_rankings',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/accession_type_ranking.txt', 'accession_type_ranking.txt')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/accession_type_ranking.txt', 'accession_type_ranking.txt'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='partition',
            field=models.CharField(choices=[('/projects/ps-yeolab3/eboyle/encode/pipeline/05_20220720/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
    ]
