# Generated by Django 4.1.1 on 2022-09-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_fastq_cells_alter_fastq_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='partition',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
    ]
