# Generated by Django 4.1.1 on 2022-09-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_skipperconfigmanifest_partition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='repeat_table',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz'), max_length=200),
        ),
    ]
