# Generated by Django 4.1.1 on 2022-09-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_skipperconfigmanifest_repeat_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='barcode_file',
            field=models.CharField(blank=True, choices=[('/projects/ps-yeolab3/eboyle/encode/pipeline/adapters/InvRiL19.fasta', 'InvRiL19_adapters.fasta')], max_length=120),
        ),
    ]
