# Generated by Django 4.1.1 on 2022-09-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_skipperconfigmanifest_barcode_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='barcode_file',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta')], default='/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', max_length=120),
        ),
    ]
