# Generated by Django 4.1.1 on 2022-09-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_skipperconfigmanifest_barcode_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='exe_dir',
            field=models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin', max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='repo_path',
            field=models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper', max_length=200),
        ),
    ]
