# Generated by Django 4.1.1 on 2022-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_skipperconfigmanifest_exe_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='umicollapse_dir',
            field=models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/UMICollapse', max_length=200),
        ),
    ]
