# Generated by Django 4.1.1 on 2022-09-30 23:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIPManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('species', models.CharField(choices=[('hg19', 'hg19'), ('GRCh38_v40', 'GRCh38_v40')], default='GRCh38_v40', max_length=20)),
                ('repeatElementGenomeDir', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2', 'star_2_7_homo_sapiens_repbase_fixed_v2'), ('/projects/ps-yeolab3/bay001/annotations/RepBase18.05/star_2_7_mus_musculus_repbase_fixed_v2', 'star_2_7_mus_musculus_repbase_fixed_v2')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2', max_length=120)),
                ('speciesGenomeDir', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/', 'star_2_7_6a_gencode19_sjdb/ (hg19)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', max_length=90)),
                ('chrom_sizes', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', 'star_2_7_gencode40_sjdb/ (GRCh38) (must match genome)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/chrNameLength.txt', 'star_2_7_6a_gencode19_sjdb/ (hg19) (must match genome)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', max_length=120)),
                ('blacklist_file', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', 'eCLIP_blacklistregions.hg38liftover.bed.fixed.bed')], default='/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', max_length=120)),
                ('umi_pattern', models.CharField(default='NNNNNNNNNN', max_length=20)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
                ('barcode_file', models.CharField(blank=True, choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SkipperConfigManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper', max_length=200)),
                ('manifest', models.CharField(default='manifest.csv', max_length=200)),
                ('gff', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200)),
                ('partition', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200)),
                ('feature_annotations', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), max_length=200)),
                ('accession_rankings', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/accession_type_ranking.txt', 'accession_type_ranking.txt')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/accession_type_ranking.txt', 'accession_type_ranking.txt'), max_length=200)),
                ('umi_size', models.IntegerField(default=10)),
                ('informative_read', models.IntegerField(default=1)),
                ('overdispersion_mode', models.CharField(choices=[('input', 'input'), ('clip', 'clip')], default=('input', 'input'), max_length=200)),
                ('conda_dir', models.CharField(blank=True, default='', max_length=200)),
                ('tool_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/tools', max_length=200)),
                ('exe_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin', max_length=200)),
                ('star_dir', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/', 'star_2_7_6a_gencode19_sjdb/ (hg19)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', 'star_2_7_gencode40_sjdb/ (GRCh38)'), max_length=90)),
                ('r_exe', models.CharField(default='/projects/ps-yeolab4/software/yeolabconda3/envs/skipper-8674296/bin/Rscript', max_length=200)),
                ('umicollapse_dir', models.CharField(default='/projects/ps-yeolab4/software/skipper/8674296/bin/UMICollapse', max_length=200)),
                ('java_exe', models.CharField(default='/projects/ps-yeolab4/software/yeolabconda3/envs/skipper-8674296/bin/java', max_length=200)),
                ('genome', models.CharField(choices=[('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta')], default=('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta'), max_length=200)),
                ('chrom_sizes', models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', 'star_2_7_gencode40_sjdb/ (GRCh38) (must match genome)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_6a_gencode19_sjdb/chrNameLength.txt', 'star_2_7_6a_gencode19_sjdb/ (hg19) (must match genome)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/chrNameLength.txt', max_length=200)),
                ('repeat_table', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/repeatmasker.grch38.tsv.gz', 'repeatmasker.grch38.tsv.gz'), max_length=200)),
                ('blacklist', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_eclip_blacklist.bed', 'encode3_eclip_blacklist.bed')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_eclip_blacklist.bed', 'encode3_eclip_blacklist.bed'), max_length=200)),
                ('gene_sets', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt', 'c5.go.v7.5.1.symbols.gmt')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/c5.go.v7.5.1.symbols.gmt', 'c5.go.v7.5.1.symbols.gmt'), max_length=200)),
                ('gene_set_reference', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz', 'encode3_go_terms.reference.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.reference.tsv.gz', 'encode3_go_terms.reference.tsv.gz'), max_length=200)),
                ('gene_set_distance', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds', 'encode3_go_terms.jaccard_index.rds')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/encode3_go_terms.jaccard_index.rds', 'encode3_go_terms.jaccard_index.rds'), max_length=200)),
                ('uninformative_read', models.IntegerField(default=2)),
                ('barcode_file', models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta')], default='/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', max_length=120)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default='EXPERIMENT', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')])),
                ('sample', models.CharField(default='SAMPLE', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')])),
                ('cells', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')])),
                ('ip_title', models.CharField(default='IP', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')])),
                ('ip_path', models.CharField(default='', max_length=255)),
                ('ip_adapter_path', models.CharField(default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255)),
                ('ip_rep', models.IntegerField(default=1)),
                ('ip_complete', models.BooleanField()),
                ('sminput_title', models.CharField(default='SMINPUT', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_]*$', 'Only alphanumeric characters are allowed.')])),
                ('sminput_path', models.CharField(default='', max_length=255)),
                ('sminput_adapter_path', models.CharField(default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255)),
                ('sminput_rep', models.IntegerField(default=1)),
                ('sminput_complete', models.BooleanField()),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
