# Generated by Django 4.1.1 on 2023-04-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnaseqmanifest',
            name='singleendfastq_ptr',
        ),
        migrations.RemoveField(
            model_name='skippermanifest',
            name='singleendfastq_ptr',
        ),
        migrations.DeleteModel(
            name='PairedEndFastq',
        ),
        migrations.DeleteModel(
            name='RnaSeqManifest',
        ),
        migrations.DeleteModel(
            name='SkipperManifest',
        ),
    ]
