# Generated by Django 4.1.1 on 2022-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipmanifest',
            name='barcode_file',
        ),
        migrations.RemoveField(
            model_name='skipperconfigmanifest',
            name='barcode_file',
        ),
        migrations.AlterField(
            model_name='fastq',
            name='ip_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255),
        ),
    ]
