# Generated by Django 4.1.1 on 2022-10-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_remove_clipmanifest_barcode_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='feature_annotations',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v41.annotation.tiled_partition.features.tsv.gz', 'gencode.v41.annotation.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='gff',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.hepg2_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.hepg2_totalrna.gt1.gff3.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='partition',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.bed.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.bed.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.hek293t.gt1.tiled_partition.bed.gz', 'gencode.v38.annotation.hek293t.gt1.tiled_partition.bed.gz'), ('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v41.annotation.tiled_partition.bed.gz', 'gencode.v41.annotation.tiled_partition.bed.gz')], default=('/projects/ps-yeolab4/software/skipper/8674296/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
    ]
