# Generated by Django 4.1.1 on 2022-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_alter_skipperconfigmanifest_accession_rankings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnaseqFastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('hg19', 'hg19'), ('mm10', 'mm10'), ('GRCh38', 'GRCh38')], max_length=20)),
                ('chrom_sizes', models.CharField(default='inputs/hg19.chrom.sizes', max_length=120)),
                ('speciesGenomeDir', models.CharField(choices=[('star_2_4_0i_gencode19_sjdb', 'star_2_4_0i_gencode19_sjdb'), ('star_2_4_0i_gencode24_sjdb', 'star_2_4_0i_gencode24_sjdb'), ('star_2_4_0i_gencode29_sjdb', 'star_2_4_0i_gencode29_sjdb'), ('star_2_4_0i_mm10_sjdb', 'star_2_4_0i_mm10_sjdb')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_gencode40_sjdb/', max_length=90)),
                ('repeatElementGenomeDir', models.CharField(choices=[('homo_sapiens_repbase_v2', 'homo_sapiens_repbase_v2'), ('mus_musculus_repbase_v2', 'mus_musculus_repbase_v2'), ('rat_rattus_repbase_v2', 'rat_rattus_repbase_v2')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/star_2_7_homo_sapiens_repbase_fixed_v2', max_length=120)),
            ],
        ),
    ]
