# Generated by Django 4.1.1 on 2022-12-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_alter_skipperconfigmanifest_accession_rankings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipmanifest',
            name='blacklist_file',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', 'eCLIP_blacklistregions.hg38liftover.bed.fixed.bed'), ('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg19.bed', 'eCLIP_blacklistregions.hg19.bed'), ('/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.noregion.bed', 'eCLIP_blacklistregions.noregion.bed')], default='/projects/ps-yeolab4/software/eclip/0.7.0/examples/inputs/eCLIP_blacklistregions.hg38liftover.bed.fixed.bed', max_length=120),
        ),
        migrations.AlterField(
            model_name='clipmanifest',
            name='species',
            field=models.CharField(choices=[('hg19', 'hg19'), ('GRCh38_v40', 'GRCh38_v40')], default='hg19', max_length=20),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='ip_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/1.0.0/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/1.0.0/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default='/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', max_length=255),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='feature_annotations',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.hepg2_totalrna.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.hek293t.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.hek293t.gt1.tiled_partition.features.tsv.gz'), ('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v41.annotation.tiled_partition.features.tsv.gz', 'gencode.v41.annotation.tiled_partition.features.tsv.gz')], default=('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz', 'gencode.v38.annotation.k562_totalrna.gt1.tiled_partition.features.tsv.gz'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='genome',
            field=models.CharField(choices=[('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta'), ('/projects/ps-yeolab3/bay001/annotations/hg19/hg19.fa', 'hg19.fa')], default=('/projects/ps-yeolab4/genomes/GRCh38/chromosomes/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta', 'GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta'), max_length=200),
        ),
        migrations.AlterField(
            model_name='skipperconfigmanifest',
            name='partition',
            field=models.CharField(choices=[], default=('/projects/ps-yeolab4/software/skipper/1.0.0/bin/skipper/annotations/gencode.v38.annotation.k562_totalrna.gt1.gff3.gz', 'gencode.v38.annotation.k562_totalrna.gt1.gff3.gz'), max_length=200),
        ),
    ]
