# Generated by Django 4.1.1 on 2022-11-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_rnaseqfastq'),
    ]

    operations = [
        migrations.AddField(
            model_name='rnaseqfastq',
            name='b_adapters',
            field=models.CharField(choices=[('inputs/adapters.fasta', 'adapters.fasta')], default='inputs/adapters.fasta', max_length=120),
        ),
        migrations.AddField(
            model_name='rnaseqfastq',
            name='direction',
            field=models.CharField(choices=[('r', 'r'), ('f', 'f')], default='r', max_length=2),
        ),
        migrations.AlterField(
            model_name='rnaseqfastq',
            name='repeatElementGenomeDir',
            field=models.CharField(choices=[('inputs/homo_sapiens_repbase_v2', 'homo_sapiens_repbase_v2'), ('inputs/mus_musculus_repbase_v2', 'mus_musculus_repbase_v2'), ('inputs/rat_rattus_repbase_v2', 'rat_rattus_repbase_v2')], max_length=120),
        ),
        migrations.AlterField(
            model_name='rnaseqfastq',
            name='speciesGenomeDir',
            field=models.CharField(choices=[('inputs/star_2_4_0i_gencode19_sjdb', 'star_2_4_0i_gencode19_sjdb'), ('inputs/star_2_4_0i_gencode24_sjdb', 'star_2_4_0i_gencode24_sjdb'), ('inputs/star_2_4_0i_gencode29_sjdb', 'star_2_4_0i_gencode29_sjdb'), ('inputs/star_2_4_0i_mm10_sjdb', 'star_2_4_0i_mm10_sjdb')], max_length=90),
        ),
    ]
