# Generated by Django 4.1.1 on 2022-11-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_rnaseqfastq_b_adapters_rnaseqfastq_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rnaseqfastq',
            name='chrom_sizes',
        ),
        migrations.AddField(
            model_name='rnaseqfastq',
            name='speciesChromSizes',
            field=models.CharField(choices=[('inputs/mm10.chrom.sizes', 'mm10.chrom.sizes'), ('inputs/hg19.chrom.sizes', 'hg19.chrom.sizes'), ('inputs/GRCh38.chrom.sizes', 'GRCh38.chrom.sizes')], default='input/hg19.chrom.sizes', max_length=200),
        ),
    ]
