# Generated by Django 4.1.1 on 2022-11-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_alter_rnaseqfastq_specieschromsizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnaseqfastq',
            name='b_adapters',
            field=models.CharField(choices=[('inputs/adapters.fasta', 'adapters.fasta')], max_length=120),
        ),
    ]
