# Generated by Django 4.1.1 on 2022-11-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_alter_rnaseqfastq_b_adapters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RnaseqFastq',
            new_name='Rnaseq',
        ),
    ]
