# Generated by Django 4.1.1 on 2022-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0010_rename_rnaseqfastq_rnaseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastq',
            name='form',
            field=models.CharField(choices=[('RnaseqSE', 'RnaseqSE'), ('RnaseqPE', 'RnaseqPE'), ('CLIP', 'CLIP')], default='', max_length=20),
        ),
    ]
