# Generated by Django 4.1.1 on 2023-01-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_alter_clipmanifest_blacklist_file_and_more'),
        ('form_builder', '0013_alter_fastq_form'),
    ]

    operations = [
    ]
