# Generated by Django 4.1.1 on 2023-01-13 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0014_merge_20230113_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='RnaseqPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('hg19', 'hg19'), ('mm10', 'mm10'), ('GRCh38', 'GRCh38')], max_length=20)),
                ('speciesChromSizes', models.CharField(choices=[('inputs/mm10.chrom.sizes', 'mm10.chrom.sizes'), ('inputs/hg19.chrom.sizes', 'hg19.chrom.sizes'), ('inputs/GRCh38.chrom.sizes', 'GRCh38.chrom.sizes')], max_length=200)),
                ('speciesGenomeDir', models.CharField(choices=[('inputs/star_2_4_0i_gencode19_sjdb', 'star_2_4_0i_gencode19_sjdb'), ('inputs/star_2_4_0i_gencode24_sjdb', 'star_2_4_0i_gencode24_sjdb'), ('inputs/star_2_4_0i_gencode29_sjdb', 'star_2_4_0i_gencode29_sjdb'), ('inputs/star_2_4_0i_mm10_sjdb', 'star_2_4_0i_mm10_sjdb')], max_length=90)),
                ('repeatElementGenomeDir', models.CharField(choices=[('inputs/homo_sapiens_repbase_v2', 'homo_sapiens_repbase_v2'), ('inputs/mus_musculus_repbase_v2', 'mus_musculus_repbase_v2'), ('inputs/rat_rattus_repbase_v2', 'rat_rattus_repbase_v2')], max_length=120)),
                ('b_adapters', models.CharField(choices=[('inputs/adapters.fasta', 'adapters.fasta')], max_length=120)),
                ('direction', models.CharField(choices=[('r', 'r'), ('f', 'f')], default='r', max_length=2)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RnaseqSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('hg19', 'hg19'), ('mm10', 'mm10'), ('GRCh38', 'GRCh38')], max_length=20)),
                ('speciesChromSizes', models.CharField(choices=[('inputs/mm10.chrom.sizes', 'mm10.chrom.sizes'), ('inputs/hg19.chrom.sizes', 'hg19.chrom.sizes'), ('inputs/GRCh38.chrom.sizes', 'GRCh38.chrom.sizes')], max_length=200)),
                ('speciesGenomeDir', models.CharField(choices=[('inputs/star_2_4_0i_gencode19_sjdb', 'star_2_4_0i_gencode19_sjdb'), ('inputs/star_2_4_0i_gencode24_sjdb', 'star_2_4_0i_gencode24_sjdb'), ('inputs/star_2_4_0i_gencode29_sjdb', 'star_2_4_0i_gencode29_sjdb'), ('inputs/star_2_4_0i_mm10_sjdb', 'star_2_4_0i_mm10_sjdb')], max_length=90)),
                ('repeatElementGenomeDir', models.CharField(choices=[('inputs/homo_sapiens_repbase_v2', 'homo_sapiens_repbase_v2'), ('inputs/mus_musculus_repbase_v2', 'mus_musculus_repbase_v2'), ('inputs/rat_rattus_repbase_v2', 'rat_rattus_repbase_v2')], max_length=120)),
                ('b_adapters', models.CharField(choices=[('inputs/adapters.fasta', 'adapters.fasta')], max_length=120)),
                ('direction', models.CharField(choices=[('r', 'r'), ('f', 'f')], default='r', max_length=2)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Rnaseq',
        ),
        migrations.AlterField(
            model_name='fastq',
            name='cells',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='experiment',
            field=models.CharField(default='EXPERIMENT', max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='ip_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), max_length=255),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='ip_title',
            field=models.CharField(default='IP', max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sample',
            field=models.CharField(default='SAMPLE', max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/8674296/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), max_length=255),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_title',
            field=models.CharField(default='SMINPUT', max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
    ]
