# Generated by Django 4.1.1 on 2023-01-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0015_rnaseqpe_rnaseqse_delete_rnaseq_alter_fastq_cells_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastq',
            name='form',
        ),
    ]
