# Generated by Django 4.1.1 on 2023-01-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0016_remove_fastq_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastq',
            name='ip_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/1.0.0/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), max_length=255),
        ),
        migrations.AlterField(
            model_name='fastq',
            name='sminput_adapter_path',
            field=models.CharField(choices=[('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta (eCLIP)'), ('/projects/ps-yeolab4/software/skipper/1.0.0/examples/InvRiL19.fasta', 'InvRiL19.fasta (SKIPPER)')], default=('/projects/ps-yeolab4/software/eclip/0.7.1/examples/inputs/InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta (eCLIP)'), max_length=255),
        ),
        migrations.AlterField(
            model_name='rnaseqpe',
            name='species',
            field=models.CharField(choices=[('hg19', 'hg19'), ('mm10', 'mm10'), ('GRCh38_v40', 'GRCh38_v40')], max_length=20),
        ),
    ]
