# Generated by Django 4.1.1 on 2023-01-27 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0017_alter_fastq_ip_adapter_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairedEndFastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default='EXPERIMENT', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('sample', models.CharField(default='SAMPLE', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('cells', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('replicate', models.IntegerField(default=1)),
                ('read1', models.CharField(default='', max_length=255)),
                ('read2', models.CharField(default='', max_length=255)),
                ('three_prime_adapters_r1', models.CharField(choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta'), ('InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta'), ('InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta'), ('InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta'), ('InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta'), ('InvRiL19.fasta', 'InvRiL19.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta'), ('InvRNA3.fasta', 'InvRNA3.fasta'), ('InvRNA4.fasta', 'InvRNA4.fasta'), ('InvRNA5.fasta', 'InvRNA5.fasta'), ('InvRNA6.fasta', 'InvRNA6.fasta'), ('InvRNA7.fasta', 'InvRNA7.fasta'), ('InvRNA8.fasta', 'InvRNA8.fasta')], max_length=200)),
                ('three_prime_adapters_r2', models.CharField(choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta'), ('InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta'), ('InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta'), ('InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta'), ('InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta'), ('InvRiL19.fasta', 'InvRiL19.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta'), ('InvRNA3.fasta', 'InvRNA3.fasta'), ('InvRNA4.fasta', 'InvRNA4.fasta'), ('InvRNA5.fasta', 'InvRNA5.fasta'), ('InvRNA6.fasta', 'InvRNA6.fasta'), ('InvRNA7.fasta', 'InvRNA7.fasta'), ('InvRNA8.fasta', 'InvRNA8.fasta')], max_length=200)),
                ('umi', models.CharField(default='NNNNNNNNNN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rnaseq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('SE', 'SE'), ('PE', 'PE')], max_length=3)),
                ('species', models.CharField(choices=[('hg19', 'hg19'), ('mm10', 'mm10'), ('GRCh38_v40', 'GRCh38_v40')], max_length=20)),
                ('speciesChromSizes', models.CharField(choices=[('inputs/mm10.chrom.sizes', 'mm10.chrom.sizes'), ('inputs/hg19.chrom.sizes', 'hg19.chrom.sizes'), ('inputs/GRCh38.chrom.sizes', 'GRCh38.chrom.sizes')], max_length=200)),
                ('speciesGenomeDir', models.CharField(choices=[('inputs/star_2_4_0i_gencode19_sjdb', 'star_2_4_0i_gencode19_sjdb'), ('inputs/star_2_4_0i_gencode24_sjdb', 'star_2_4_0i_gencode24_sjdb'), ('inputs/star_2_4_0i_gencode29_sjdb', 'star_2_4_0i_gencode29_sjdb'), ('inputs/star_2_4_0i_mm10_sjdb', 'star_2_4_0i_mm10_sjdb')], max_length=90)),
                ('repeatElementGenomeDir', models.CharField(choices=[('inputs/homo_sapiens_repbase_v2', 'homo_sapiens_repbase_v2'), ('inputs/mus_musculus_repbase_v2', 'mus_musculus_repbase_v2'), ('inputs/rat_rattus_repbase_v2', 'rat_rattus_repbase_v2')], max_length=120)),
                ('b_adapters', models.CharField(choices=[('inputs/adapters.fasta', 'adapters.fasta')], max_length=120)),
                ('direction', models.CharField(choices=[('r', 'r'), ('f', 'f')], default='r', max_length=2)),
                ('fastqs', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SingleEndFastq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.CharField(default='EXPERIMENT', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('sample', models.CharField(default='SAMPLE', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('cells', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('replicate', models.IntegerField(default=1)),
                ('read1', models.CharField(default='', max_length=255)),
                ('three_prime_adapters_clip', models.CharField(choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta'), ('InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta'), ('InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta'), ('InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta'), ('InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta')], max_length=200)),
                ('three_prime_adapters_skipper', models.CharField(choices=[('InvRiL19.fasta', 'InvRiL19.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta'), ('InvRNA3.fasta', 'InvRNA3.fasta'), ('InvRNA4.fasta', 'InvRNA4.fasta'), ('InvRNA5.fasta', 'InvRNA5.fasta'), ('InvRNA6.fasta', 'InvRNA6.fasta'), ('InvRNA7.fasta', 'InvRNA7.fasta'), ('InvRNA8.fasta', 'InvRNA8.fasta')], max_length=200)),
                ('three_prime_adapters', models.CharField(choices=[('InvRiL19_adapters.fasta', 'InvRiL19_adapters.fasta'), ('InvRNA1_adapters.fasta', 'InvRNA1_adapters.fasta'), ('InvRNA2_adapters.fasta', 'InvRNA2_adapters.fasta'), ('InvRNA3_adapters.fasta', 'InvRNA3_adapters.fasta'), ('InvRNA4_adapters.fasta', 'InvRNA4_adapters.fasta'), ('InvRNA5_adapters.fasta', 'InvRNA5_adapters.fasta'), ('InvRNA6_adapters.fasta', 'InvRNA6_adapters.fasta'), ('InvRNA7_adapters.fasta', 'InvRNA7_adapters.fasta'), ('InvRNA8_adapters.fasta', 'InvRNA8_adapters.fasta'), ('InvRiL19.fasta', 'InvRiL19.fasta'), ('InvRNA1.fasta', 'InvRNA1.fasta'), ('InvRNA2.fasta', 'InvRNA2.fasta'), ('InvRNA3.fasta', 'InvRNA3.fasta'), ('InvRNA4.fasta', 'InvRNA4.fasta'), ('InvRNA5.fasta', 'InvRNA5.fasta'), ('InvRNA6.fasta', 'InvRNA6.fasta'), ('InvRNA7.fasta', 'InvRNA7.fasta'), ('InvRNA8.fasta', 'InvRNA8.fasta')], max_length=200)),
                ('umi', models.CharField(default='NNNNNNNNNN', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RnaseqPE',
        ),
        migrations.DeleteModel(
            name='RnaseqSE',
        ),
        migrations.CreateModel(
            name='ClipperSingleEndFastq',
            fields=[
                ('singleendfastq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form_builder.singleendfastq')),
            ],
            options={
                'abstract': False,
            },
            bases=('form_builder.singleendfastq',),
        ),
        migrations.CreateModel(
            name='RnaSeqSingleEndFastq',
            fields=[
                ('singleendfastq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form_builder.singleendfastq')),
            ],
            options={
                'abstract': False,
            },
            bases=('form_builder.singleendfastq',),
        ),
        migrations.CreateModel(
            name='SkipperSingleEndFastq',
            fields=[
                ('singleendfastq_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form_builder.singleendfastq')),
            ],
            options={
                'abstract': False,
            },
            bases=('form_builder.singleendfastq',),
        ),
    ]
