# Generated by Django 4.1.1 on 2023-03-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0019_delete_clipmanifest_remove_fastq_submitter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClipperSingleEndFastq',
            new_name='ClipperManifest',
        ),
        migrations.RenameModel(
            old_name='RnaSeqSingleEndFastq',
            new_name='RnaSeqManifest',
        ),
        migrations.RenameModel(
            old_name='SkipperSingleEndFastq',
            new_name='SkipperManifest',
        ),
    ]
