# Generated by Django 4.1.1 on 2023-03-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0020_rename_clippersingleendfastq_clippermanifest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clippermanifest',
            name='singleendfastq_ptr',
        ),
        migrations.AddField(
            model_name='clippermanifest',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
